import type { BankQuestion } from "@/content/interview/types";

/** Quantitative, logical reasoning and verbal ability — the usual first round. */
export const aptitudeBank: BankQuestion[] = [
  {
    id: "apt-quant-01",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Speed, time & distance",
    prompt: "A train 150 metres long crosses an electric pole in 15 seconds. What is its speed?",
    options: ["36 km/h", "45 km/h", "54 km/h", "60 km/h"],
    answerIndex: 0,
    explanation: "Crossing a pole means covering its own length: 150 ÷ 15 = 10 m/s. Multiply by 18/5 to get 36 km/h.",
    minutes: 2,
  },
  {
    id: "apt-quant-02",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Percentages",
    prompt: "The price of a laptop is increased by 20% and then reduced by 20%. What is the net change?",
    options: ["No change", "4% decrease", "4% increase", "2% decrease"],
    answerIndex: 1,
    explanation: "1.20 × 0.80 = 0.96, so the final price is 96% of the original — a 4% decrease.",
    minutes: 2,
  },
  {
    id: "apt-quant-03",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Ratio & proportion",
    prompt: "Two numbers are in the ratio 3 : 4 and add up to 84. What is the larger number?",
    options: ["36", "42", "48", "56"],
    answerIndex: 2,
    explanation: "3x + 4x = 84, so x = 12. The numbers are 36 and 48.",
    minutes: 2,
  },
  {
    id: "apt-quant-04",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Time & work",
    prompt: "A finishes a job in 12 days and B in 18 days. Working together, how long do they take?",
    options: ["6 days", "7.2 days", "8 days", "9 days"],
    answerIndex: 1,
    explanation: "Combined rate = 1/12 + 1/18 = 5/36 of the job per day, so the job takes 36/5 = 7.2 days.",
    minutes: 2,
  },
  {
    id: "apt-quant-05",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Averages",
    prompt: "The average of five numbers is 27. If the number 35 is removed, what is the average of the rest?",
    options: ["23", "25", "26", "28"],
    answerIndex: 1,
    explanation: "Total = 5 × 27 = 135. Without 35, the total is 100 across four numbers, so the average is 25.",
    minutes: 2,
  },
  {
    id: "apt-quant-06",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Compound interest",
    prompt: "What is the compound interest on ₹10,000 at 10% per annum for 2 years, compounded annually?",
    options: ["₹2,000", "₹2,100", "₹2,210", "₹1,900"],
    answerIndex: 1,
    explanation: "Amount = 10,000 × 1.1² = ₹12,100, so the interest is ₹2,100.",
    minutes: 2,
  },
  {
    id: "apt-quant-07",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Profit & loss",
    prompt: "A shopkeeper buys an item for ₹400 and sells it at a 20% profit. What is the selling price?",
    options: ["₹420", "₹440", "₹480", "₹500"],
    answerIndex: 2,
    explanation: "Profit = 20% of 400 = ₹80, so the selling price is ₹480.",
    minutes: 1,
  },
  {
    id: "apt-quant-08",
    round: "APTITUDE",
    kind: "MCQ",
    level: "INTERMEDIATE",
    topic: "Average speed",
    prompt: "A car covers 60 km at 30 km/h and returns along the same route at 60 km/h. What is the average speed for the whole trip?",
    options: ["40 km/h", "45 km/h", "48 km/h", "50 km/h"],
    answerIndex: 0,
    explanation: "Average speed = 2ab/(a+b) = (2 × 30 × 60)/90 = 40 km/h. It is not the plain average of the two speeds.",
    minutes: 3,
  },
  {
    id: "apt-quant-09",
    round: "APTITUDE",
    kind: "MCQ",
    level: "INTERMEDIATE",
    topic: "Probability",
    prompt: "A fair die is rolled twice. What is the probability that the two rolls add up to 8?",
    options: ["1/6", "5/36", "1/9", "7/36"],
    answerIndex: 1,
    explanation: "The pairs are (2,6), (3,5), (4,4), (5,3) and (6,2) — 5 outcomes out of 36.",
    minutes: 3,
  },
  {
    id: "apt-quant-10",
    round: "APTITUDE",
    kind: "MCQ",
    level: "INTERMEDIATE",
    topic: "Permutations",
    prompt: "How many distinct arrangements can be made from the letters of the word LEVEL?",
    options: ["20", "30", "60", "120"],
    answerIndex: 1,
    explanation: "5 letters with L twice and E twice: 5!/(2! × 2!) = 120/4 = 30.",
    minutes: 3,
  },
  {
    id: "apt-quant-11",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Number system",
    prompt: "What is the highest common factor (HCF) of 36 and 60?",
    options: ["6", "12", "18", "24"],
    answerIndex: 1,
    explanation: "36 = 2² × 3², 60 = 2² × 3 × 5. Common factors: 2² × 3 = 12.",
    minutes: 1,
  },
  {
    id: "apt-quant-12",
    round: "APTITUDE",
    kind: "MCQ",
    level: "INTERMEDIATE",
    topic: "Ages",
    prompt: "A father is three times as old as his son. In 12 years he will be twice as old. How old is the father now?",
    options: ["30", "36", "40", "45"],
    answerIndex: 1,
    explanation: "If the son is s, then 3s + 12 = 2(s + 12), so s = 12 and the father is 36.",
    minutes: 3,
  },
  {
    id: "apt-logic-01",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Number series",
    prompt: "Find the next number: 2, 6, 12, 20, 30, ?",
    options: ["36", "40", "42", "44"],
    answerIndex: 2,
    explanation: "The gaps are 4, 6, 8, 10, so the next gap is 12: 30 + 12 = 42.",
    minutes: 2,
  },
  {
    id: "apt-logic-02",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Number series",
    prompt: "Find the next number: 3, 9, 27, 81, ?",
    options: ["162", "216", "243", "324"],
    answerIndex: 2,
    explanation: "Each term is multiplied by 3, so 81 × 3 = 243.",
    minutes: 1,
  },
  {
    id: "apt-logic-03",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Odd one out",
    prompt: "Which one does not belong: 121, 144, 169, 200?",
    options: ["121", "144", "169", "200"],
    answerIndex: 3,
    explanation: "121 = 11², 144 = 12², 169 = 13². 200 is not a perfect square.",
    minutes: 1,
  },
  {
    id: "apt-logic-04",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Coding & decoding",
    prompt: "If FACE is written as GBDF, how is BOOK written in the same code?",
    options: ["CPPL", "CPLP", "BPPL", "CPPK"],
    answerIndex: 0,
    explanation: "Each letter moves one step forward: B→C, O→P, O→P, K→L.",
    minutes: 2,
  },
  {
    id: "apt-logic-05",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Blood relations",
    prompt: "Pointing at a photograph, Raj says, “He is the son of my father's only son.” Who is in the photograph?",
    options: ["Raj's brother", "Raj's son", "Raj's father", "Raj's nephew"],
    answerIndex: 1,
    explanation: "His father's only son is Raj himself, so the photograph shows Raj's son.",
    minutes: 2,
  },
  {
    id: "apt-logic-06",
    round: "APTITUDE",
    kind: "MCQ",
    level: "INTERMEDIATE",
    topic: "Directions",
    prompt: "Ravi walks 5 km north, turns right and walks 3 km, then turns right again and walks 5 km. How far is he from his starting point?",
    options: ["3 km", "5 km", "8 km", "13 km"],
    answerIndex: 0,
    explanation: "The two 5 km legs cancel out (north then south), leaving him 3 km east of where he started.",
    minutes: 3,
  },
  {
    id: "apt-logic-07",
    round: "APTITUDE",
    kind: "MCQ",
    level: "INTERMEDIATE",
    topic: "Syllogisms",
    prompt: "All roses are flowers. Some flowers fade quickly. Which conclusion definitely follows?",
    options: [
      "Some roses fade quickly",
      "No rose fades quickly",
      "All flowers are roses",
      "Neither conclusion definitely follows",
    ],
    answerIndex: 3,
    explanation: "The flowers that fade quickly may be entirely outside the set of roses, so nothing definite follows about roses.",
    minutes: 3,
  },
  {
    id: "apt-logic-08",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Analogies",
    prompt: "Doctor : Patient :: Teacher : ?",
    options: ["School", "Student", "Book", "Lesson"],
    answerIndex: 1,
    explanation: "A doctor serves a patient just as a teacher serves a student.",
    minutes: 1,
  },
  {
    id: "apt-logic-09",
    round: "APTITUDE",
    kind: "MCQ",
    level: "INTERMEDIATE",
    topic: "Calendars",
    prompt: "If 1 January 2024 is a Monday, what day is 1 February 2024?",
    options: ["Wednesday", "Thursday", "Friday", "Saturday"],
    answerIndex: 1,
    explanation: "January has 31 days; 31 ÷ 7 leaves 3. Monday + 3 days = Thursday.",
    minutes: 3,
  },
  {
    id: "apt-logic-10",
    round: "APTITUDE",
    kind: "MCQ",
    level: "INTERMEDIATE",
    topic: "Clocks",
    prompt: "What is the angle between the hands of a clock at 3:30?",
    options: ["60°", "75°", "80°", "90°"],
    answerIndex: 1,
    explanation: "Angle = |30H − 5.5M| = |90 − 165| = 75°.",
    minutes: 3,
  },
  {
    id: "apt-verbal-01",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Synonyms",
    prompt: "Choose the word closest in meaning to “meticulous”.",
    options: ["Careless", "Careful", "Generous", "Hesitant"],
    answerIndex: 1,
    explanation: "Meticulous means showing great attention to detail — careful.",
    minutes: 1,
  },
  {
    id: "apt-verbal-02",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Antonyms",
    prompt: "Choose the word opposite in meaning to “scarce”.",
    options: ["Rare", "Limited", "Abundant", "Costly"],
    answerIndex: 2,
    explanation: "Scarce means in short supply; abundant means plentiful.",
    minutes: 1,
  },
  {
    id: "apt-verbal-03",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Grammar",
    prompt: "Which sentence is correct?",
    options: [
      "He is one of the best player in the team.",
      "He is one of the best players in the team.",
      "He is one of the better player in the team.",
      "He is one of best players in team.",
    ],
    answerIndex: 1,
    explanation: "“One of the …” is always followed by a plural noun: one of the best players.",
    minutes: 2,
  },
  {
    id: "apt-verbal-04",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Vocabulary in context",
    prompt: "The manager was ___ about the delay and apologised to every client personally.",
    options: ["indifferent", "apologetic", "delighted", "evasive"],
    answerIndex: 1,
    explanation: "Apologising to every client shows he was apologetic.",
    minutes: 1,
  },
  {
    id: "apt-verbal-05",
    round: "APTITUDE",
    kind: "MCQ",
    level: "INTERMEDIATE",
    topic: "Idioms",
    prompt: "What does the idiom “bite the bullet” mean?",
    options: [
      "To face something difficult with courage",
      "To speak without thinking",
      "To waste an opportunity",
      "To argue stubbornly",
    ],
    answerIndex: 0,
    explanation: "It means to accept something unpleasant and get on with it.",
    minutes: 1,
  },
  {
    id: "apt-verbal-06",
    round: "APTITUDE",
    kind: "MCQ",
    level: "INTERMEDIATE",
    topic: "Error spotting",
    prompt: "Find the error: “Each of the students have submitted the assignment on time.”",
    options: ["Each of", "the students", "have submitted", "on time"],
    answerIndex: 2,
    explanation: "“Each” is singular, so it takes “has submitted”.",
    minutes: 2,
  },
  {
    id: "apt-verbal-07",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Spelling",
    prompt: "Which word is spelled correctly?",
    options: ["Occurence", "Ocurrence", "Occurrence", "Occurrance"],
    answerIndex: 2,
    explanation: "Occurrence has double c and double r.",
    minutes: 1,
  },
  {
    id: "apt-verbal-08",
    round: "APTITUDE",
    kind: "MCQ",
    level: "BEGINNER",
    topic: "Prepositions",
    prompt: "She has been working at this company ___ 2019.",
    options: ["from", "since", "for", "during"],
    answerIndex: 1,
    explanation: "“Since” is used with a point in time; “for” would need a duration, such as “for six years”.",
    minutes: 1,
  },
];
