/**
 * Prints the starter interview bank as SQL for a migration:
 *   npx tsx scripts/generate-interview-seed.ts > prisma/migrations/<id>/migration.sql
 *
 * Rows are inserted by their stable id and skipped if already present, so the
 * migration never overwrites questions an admin has edited.
 */
import { interviewBank } from "../src/content/interview";

const text = (v: string | undefined | null) => (v === undefined || v === null ? "NULL" : `'${v.replace(/'/g, "''")}'`);
const array = (v: string[] | undefined) => (v?.length ? `ARRAY[${v.map((s) => text(s)).join(", ")}]::text[]` : "ARRAY[]::text[]");
const num = (v: number | undefined | null) => (v === undefined || v === null ? "NULL" : String(v));

const rows = interviewBank.map((q) =>
  [
    text(q.id),
    `${text(q.round)}::"InterviewRound"`,
    `${text(q.kind)}::"InterviewKind"`,
    `${text(q.level)}::"Level"`,
    text(q.topic),
    text(q.prompt),
    array(q.domainTags),
    array(q.options),
    num(q.answerIndex),
    text(q.modelAnswer),
    text(q.explanation),
    text(q.starterCode),
    text(q.language),
    array(q.hints),
    num(q.minutes ?? 3),
    "true",
    "false",
    "now()",
    "now()",
  ].join(", "),
);

console.log(`-- Starter interview question bank (${interviewBank.length} questions).
-- Generated by scripts/generate-interview-seed.ts — edit the content files and regenerate.

INSERT INTO "InterviewQuestion" (
  "id", "round", "kind", "level", "topic", "prompt", "domainTags", "options", "answerIndex",
  "modelAnswer", "explanation", "starterCode", "language", "hints", "minutes", "isActive", "isSample",
  "createdAt", "updatedAt"
) VALUES
${rows.map((r) => `  (${r})`).join(",\n")}
ON CONFLICT ("id") DO NOTHING;`);
